<?php

use Bohdan\HelloWorld\Block\Display;

/**
 * @var Display $block
 */
?>

<div class="row">
    <div class="col-md-8">
        <form name="addData" method="get" id="addData" class="form"
              action="<?php echo $this->getUrl('main/index/test'); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Write a title of a book')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                    escapeHtmlAttr(__('Book title')) ?></span></label>
                            <div class="control">
                                <input name="title" id="title" title="Book Title" value="" class="input-text" type="text"
                                       data-validate="{required:true}">
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                            escapeHtmlAttr(__('Find')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>
