<?php

namespace Dev\Grid\Model\ResourceModel\Phone;

use Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;
use Dev\Grid\Model\Phone as Model;
use Dev\Grid\Model\ResourceModel\Phone as ResourceModel;

class Collection extends AbstractCollection
{
    /**
     * @var string
     */
    protected $_eventPrefix = 'phone_collection';

    protected function _construct()
    {
        $this->_init(Model::class, ResourceModel::class);
    }
    protected function _beforeLoad()
    {
        return parent::_beforeLoad(); // TODO: Change the autogenerated stub
    }

}
