<?php

namespace Bohdan\HelloWorld\Model\ResourceModel\Book;

use Bohdan\HelloWorld\Model\Book as Model;
use Bohdan\HelloWorld\Model\ResourceModel\Book as ResourceModel;
use Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;

class Collection extends AbstractCollection
{
    /**
     * @var string
     */
    protected $_eventPrefix = 'book_collection';

    /**
     * Initialize collection model.
     */
    protected function _construct()
    {
        $this->_init(Model::class, ResourceModel::class);
    }

    protected function _beforeLoad()
    {
        return parent::_beforeLoad(); // TODO: Change the autogenerated stub
    }

    public function testLeftJoin()
    {
        $authorTable = $this->getTable('author');
        $this->getSelect()->joinLeft([$authorTable], "main_table.author_id = author.author_id");
        return $this;
    }

}
