<?php

namespace Tasks\TotalCollector\Model\Total\Quote;

use Magento\Quote\Model\Quote\Address\Total\AbstractTotal;

class Custom extends AbstractTotal
{
    public function collect(\Magento\Quote\Model\Quote $quote, \Magento\Quote\Api\Data\ShippingAssignmentInterface $shippingAssignment, \Magento\Quote\Model\Quote\Address\Total $total)
    {
        parent::collect($quote, $shippingAssignment, $total); // TODO: Change the autogenerated stub

        $discount = 0.1 * $quote->getGrandTotal();
        $total->addTotalAmount($this->getCode(), - $discount);
        $total->addBaseTotalAmount($this->getCode(), - $discount);
        $quote->setDiscount($discount);

        return $this;
    }

    public function fetch(\Magento\Quote\Model\Quote $quote, \Magento\Quote\Model\Quote\Address\Total $total)
    {
        $discount = 0.1 * $quote->getGrandTotal();
        return [
            'code' => $this->getCode(),
            'title' => $this->getLabel(),
            'value' => $discount  //You can change the reduced amount, or replace it with your own variable
        ];
    }
}
